---
deployment:
  tasks:
    - export DEPLOYPATH_API=/home/araratch/api.araratchile.com/
    - export DEPLOYPATH_APP=/home/araratch/app.araratchile.com/
    - /bin/cp -R backend/* $DEPLOYPATH_API
    - /bin/cp -R frontend/dist/* $DEPLOYPATH_APP





###