# Generated by Django 6.0.7 on 2026-07-14 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='maquinas/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='asignado_a',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='cliente',
        ),
        migrations.CreateModel(
            name='ReservaMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoMaestranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('SOLDADURA', 'Soldadura'), ('TORNO', 'Torno mecánico'), ('INSUMOS', 'Insumos ferretería'), ('REPUESTOS', 'Repuestos industriales'), ('FLEXIBLES', 'Flexibles hidráulicos')], max_length=20)),
                ('descripcion', models.TextField()),
                ('centro_costo', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='maestranza/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('TERMINADO', 'Terminado')], default='PENDIENTE', max_length=20)),
                ('avance', models.PositiveSmallIntegerField(default=0)),
                ('tiempo_entrega', models.DateField(blank=True, null=True)),
                ('modalidad_entrega', models.CharField(blank=True, choices=[('RETIRO', 'Retiro en local'), ('DELIVERY', 'Delivery')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_maestranza', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Evidencia',
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
