# Generated by Django 6.0.7 on 2026-07-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_maquina_precio_dia_maquina_precio_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservamaquina',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reservamaquina',
            name='modalidad_entrega',
            field=models.CharField(choices=[('RETIRO', 'Retira en local'), ('DELIVERY', 'Entrega en obra')], default='RETIRO', max_length=20),
        ),
    ]
