# Generated by Django 6.0.7 on 2026-07-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reservamaquina_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialusado',
            name='unidad',
        ),
    ]
