# Generated by Django 6.0.7 on 2026-07-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_materialusado_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajomaestranza',
            name='tiempo_entrega',
        ),
        migrations.AddField(
            model_name='trabajomaestranza',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
