# Generated by Django 6.0.7 on 2026-07-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_trabajomaestranza_tiempo_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajomaestranza',
            name='tiempo_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
