# Generated by Django 6.0.7 on 2026-07-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_trabajomaestranza_tiempo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajomaestranza',
            name='fecha_retraso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajomaestranza',
            name='motivo_retraso',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trabajomaestranza',
            name='retrasado',
            field=models.BooleanField(default=False),
        ),
    ]
