# Generated by Django 6.0.7 on 2026-07-16 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_solicitudmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('rut', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='solicitudmaterial',
            name='lugar_compra',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trabajomaestranza',
            name='correlativo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solicitudmaterial',
            name='estado',
            field=models.CharField(choices=[('REVISION', 'En revisión'), ('PENDIENTE', 'Pendiente de compra'), ('RECIBIDO', 'Recibido')], default='REVISION', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='core.empresa'),
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsables', to='core.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='trabajomaestranza',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos', to='core.responsable'),
        ),
    ]
