# Generated by Django 6.0.7 on 2026-07-20 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_empresa_solicitudmaterial_lugar_compra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_trabajo', to=settings.AUTH_USER_MODEL)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.trabajomaestranza')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
