# Generated by Django 6.0.7 on 2026-07-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_comentariotrabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialusado',
            name='unidad',
            field=models.CharField(choices=[('m', 'Metros (m)'), ('m2', 'Metros cuadrados (m²)'), ('kg', 'Kilos (kg)'), ('un', 'Unidades'), ('lt', 'Litros (lt)'), ('plancha', 'Planchas'), ('barra', 'Barras'), ('rollo', 'Rollos')], default='un', max_length=20),
        ),
    ]
