# Generated by Django 6.0.7 on 2026-07-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_materialusado_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialusado',
            name='unidad',
        ),
        migrations.AlterField(
            model_name='materialusado',
            name='cantidad',
            field=models.CharField(max_length=50),
        ),
    ]
