# Generated by Django 6.0.7 on 2026-07-20 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_materialusado_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariotrabajo',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_trabajo', to='core.responsable'),
        ),
    ]
