# Generated by Django 6.0.7 on 2026-07-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_comentariotrabajo_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
