# Generated by Django 6.0.7 on 2026-07-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_empresa_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoFerreteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('categoria', models.CharField(choices=[('INSUMOS', 'Insumos ferretería'), ('REPUESTOS', 'Repuestos industriales')], max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='ferreteria/')),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
