# Generated by Django 6.0.7 on 2026-07-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pedidoferreteria_itempedidoferreteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoferreteria',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productoferreteria',
            name='sku',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
