# Generated by Django 6.0.7 on 2026-07-24 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_itempedidoferreteria_precio_itempedidoferreteria_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoFlexible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MANGUERA_R1', 'Manguera R1'), ('MANGUERA_R2', 'Manguera R2'), ('TERMINAL_JIC', 'Terminal JIC'), ('TERMINAL_HEMBRA_RECTO', 'Terminal Hembra Recto'), ('TERMINAL_MACHO_RECTO', 'Terminal Macho Recto'), ('TERMINAL_H45', 'Terminal H45'), ('TERMINAL_H90', 'Terminal H90'), ('FERULA', 'Férula')], max_length=30)),
                ('diametro', models.CharField(blank=True, max_length=20)),
                ('unidad_medida', models.CharField(choices=[('METRO', 'Metro'), ('UNIDAD', 'Unidad')], max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tipo', 'diametro'],
            },
        ),
        migrations.CreateModel(
            name='FlexibleDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_manguera', models.CharField(choices=[('R1', 'R1'), ('R2', 'R2')], max_length=5)),
                ('diametro', models.CharField(max_length=20)),
                ('largo_metros', models.DecimalField(decimal_places=2, max_digits=6)),
                ('terminal_entrada', models.CharField(choices=[('TERMINAL_JIC', 'JIC'), ('TERMINAL_HEMBRA_RECTO', 'Hembra Recto'), ('TERMINAL_MACHO_RECTO', 'Macho Recto'), ('TERMINAL_H45', 'H45'), ('TERMINAL_H90', 'H90')], max_length=30)),
                ('terminal_salida', models.CharField(choices=[('TERMINAL_JIC', 'JIC'), ('TERMINAL_HEMBRA_RECTO', 'Hembra Recto'), ('TERMINAL_MACHO_RECTO', 'Macho Recto'), ('TERMINAL_H45', 'H45'), ('TERMINAL_H90', 'H90')], max_length=30)),
                ('cantidad_ferulas', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2')], default=2)),
                ('stock_descontado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_flexible', to='core.trabajomaestranza')),
            ],
        ),
    ]
