# Generated by Django 6.0.7 on 2026-07-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_productoflexible_flexibledetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexibledetalle',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
