# Generated by Django 6.0.7 on 2026-07-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_flexibledetalle_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexibledetalle',
            name='terminal_entrada',
            field=models.CharField(blank=True, choices=[('TERMINAL_JIC', 'JIC'), ('TERMINAL_HEMBRA_RECTO', 'Hembra Recto'), ('TERMINAL_MACHO_RECTO', 'Macho Recto'), ('TERMINAL_H45', 'H45'), ('TERMINAL_H90', 'H90')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='flexibledetalle',
            name='terminal_salida',
            field=models.CharField(blank=True, choices=[('TERMINAL_JIC', 'JIC'), ('TERMINAL_HEMBRA_RECTO', 'Hembra Recto'), ('TERMINAL_MACHO_RECTO', 'Macho Recto'), ('TERMINAL_H45', 'H45'), ('TERMINAL_H90', 'H90')], max_length=30, null=True),
        ),
    ]
