# Generated by Django 6.0.7 on 2026-07-27 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_flexibledetalle_terminal_entrada_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoflexible',
            options={'ordering': ['categoria', 'nombre', 'diametro']},
        ),
        migrations.RemoveField(
            model_name='flexibledetalle',
            name='diametro',
        ),
        migrations.RemoveField(
            model_name='flexibledetalle',
            name='tipo_manguera',
        ),
        migrations.RemoveField(
            model_name='productoflexible',
            name='tipo',
        ),
        migrations.AddField(
            model_name='flexibledetalle',
            name='ferula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_ferula', to='core.productoflexible'),
        ),
        migrations.AddField(
            model_name='flexibledetalle',
            name='manguera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_manguera', to='core.productoflexible'),
        ),
        migrations.AddField(
            model_name='productoflexible',
            name='categoria',
            field=models.CharField(choices=[('MANGUERA', 'Manguera'), ('TERMINAL', 'Terminal'), ('FERULA', 'Férula')], default='MANGUERA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoflexible',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flexibledetalle',
            name='terminal_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_terminal_entrada', to='core.productoflexible'),
        ),
        migrations.AlterField(
            model_name='flexibledetalle',
            name='terminal_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_terminal_salida', to='core.productoflexible'),
        ),
    ]
