# Generated by Django 6.0.7 on 2026-07-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_productoflexible_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='precio_mes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservamaquina',
            name='dias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservamaquina',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservamaquina',
            name='precio_neto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservamaquina',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservamaquina',
            name='tarifa_aplicada',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
