# Generated by Django 6.0.7 on 2026-07-28 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_productogas_pedidogas_itempedidogas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=20)),
                ('obra', models.CharField(blank=True, max_length=255)),
                ('mandante', models.CharField(blank=True, max_length=255)),
                ('lugar_trabajo', models.CharField(blank=True, max_length=255)),
                ('validez_dias', models.PositiveIntegerField(default=10)),
                ('items', models.JSONField(default=list)),
                ('notas', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='core.empresa')),
                ('trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='core.trabajomaestranza')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
