# Generated by Django 6.0.7 on 2026-07-28 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asignado_a', models.ForeignKey(blank=True, limit_choices_to={'rol': 'TRABAJADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
                ('trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_agenda', to='core.trabajomaestranza')),
            ],
            options={
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
