# Generated by Django 6.0.7 on 2026-07-28 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_tareaagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='precio_despacho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservamaquina',
            name='precio_despacho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reservamaquina',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_maquina', to='core.responsable'),
        ),
    ]
