# Generated by Django 6.0.7 on 2026-07-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_maquina_precio_despacho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservamaquina',
            name='visto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservamaquina',
            name='modalidad_entrega',
            field=models.CharField(choices=[('RETIRO', 'Retira en local'), ('DESPACHO', 'Entrega en obra')], default='RETIRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajomaestranza',
            name='modalidad_entrega',
            field=models.CharField(blank=True, choices=[('RETIRO', 'Retiro en local'), ('DESPACHO', 'Despacho')], max_length=20, null=True),
        ),
    ]
