# Generated by Django 6.0.7 on 2026-07-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_reservamaquina_visto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajomaestranza',
            name='categoria',
            field=models.CharField(choices=[('SOLDADURA', 'Soldadura'), ('TORNO', 'Torno mecánico'), ('INSUMOS', 'Insumos ferretería'), ('REPUESTOS', 'Repuestos industriales'), ('FLEXIBLES', 'Flexibles hidráulicos'), ('FABRICACION', 'Fabricación de equipos especiales y proyecto')], max_length=20),
        ),
    ]
