# Generated by Django 6.0.7 on 2026-07-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_trabajomaestranza_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariotrabajo',
            name='visto_admin',
            field=models.BooleanField(default=True),
        ),
    ]
