# Generated by Django 6.0.7 on 2026-07-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_comentariotrabajo_visto_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
