# Generated by Django 6.0.7 on 2026-07-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_cotizacion_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='orden_trabajo_manual',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
