# Generated by Django 6.0.7 on 2026-07-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_cotizacion_orden_trabajo_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='folio',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
