# Generated by Django 6.0.7 on 2026-08-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservamaquina',
            name='fecha_aceptacion_terminos',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservamaquina',
            name='terminos_aceptados',
            field=models.BooleanField(default=False),
        ),
    ]
