# Generated by Django 6.0.7 on 2026-08-06 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_reservamaquina_fecha_aceptacion_terminos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='reserva_maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='core.reservamaquina'),
        ),
    ]
