# Generated by Django 6.0.7 on 2026-08-06 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_cotizacion_reserva_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='pedido_ferreteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='core.pedidoferreteria'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='pedido_gas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='core.pedidogas'),
        ),
    ]
