# Generated by Django 6.0.7 on 2026-08-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_cotizacion_pedido_ferreteria_cotizacion_pedido_gas'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='categoria',
            field=models.CharField(blank=True, choices=[('AUTOCARGABLE', 'Autocargable'), ('GRUA_HORQUILLA', 'Grúa Horquilla')], default='', max_length=20),
        ),
    ]
