# Generated by Django 6.0.7 on 2026-08-07 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_maquina_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias_maquinas/')),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='maquina',
            name='categoria_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maquinas', to='core.categoriamaquina'),
        ),
    ]
