# Generated by Django 6.0.7 on 2026-08-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_categoriamaquina_maquina_categoria_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maquina',
            name='categoria',
        ),
    ]
