# Generated by Django 6.0.7 on 2026-08-12 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_maquina_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='maestranza/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.trabajomaestranza')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
